### ISSUE TITLE
youtube music is taking longer than usual to load

### ISSUE THREAD

**Issue by Vascare** [adlerluiz/ytmdesktop#1349]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

wehn i boot ytm desktop app its stuck in a boot loop with the message  "youtube music is taking longer than usual to load"
i tried to reinstall it, delete all files and ofc closing it completly and boot it 
![image](https://github.com/ytmdesktop/ytmdesktop/assets/75822073/18d6aaaa-958a-462d-a6ba-4fb3933ecd8b)

### Expected Behavior

that it boots normaly so i can hear some music

### Steps To Reproduce

Open YTM Desktop app 
and then its loading 

### YTMDesktop

v 2.0.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

hope i filled out everything right 
and sorry for my bad english

**Comment by Pesoen** [comment]
Same issue here, old version(1.12.0) works just fine, so unsure what is causing the new version to not load correctly, but that is a workaround for now, to just install an older version.

tried messing with settings, pressing home button, nothing seems to alter the behavior. unsure if earlier version of the rewrite worked, and it's a new problem with 2.0.2(HEAD) been a while since i last used the app, and just stuck with older version since it worked fine.

Disabling hardware acceleration does nothing, any other setting also does nothing to get it working.

changing network, and even computer does not change anything either. still stuck on loading, after update check. same behavior on two separate machines, on separate networks, with different specs. either a code issue, api issue or other issue.

**Comment by Alipoodle** [comment]
The GitHub Repo has been down for the last 2 months due to a issue with a compromised account.

This issue has been fixed in a v2.0.3 release however, we couldn't deploy it for people to auto update with due to the lack of the GitHub repo existing.
We've currently got some outstanding fixes needed before we'll be releasing a v2.0.4 version.

**Comment by Vascare** [comment]
> The GitHub Repo has been down for the last 2 months due to a issue with a compromised account.
> 
> This issue has been fixed in a v2.0.3 release however, we couldn't deploy it for people to auto update with due to the lack of the GitHub repo existing. We've currently got some outstanding fixes needed before we'll be releasing a v2.0.4 version.

ahhh 
understandable thank you for the fast reply Alipoodle :D

**Comment by trueTrueman** [comment]
I have this issue on v.2.0.5. It loads in the end, though it takes exactly 42 seconds to load every time.

**Comment by naruko-hstk** [comment]
v2.0.5 on macOS Sonoma got `taking longer than usual to load`.

**Comment by ncihnegn** [comment]
Should reopen it.

**Comment by Wesleyzxc** [comment]
I was having it on 2.0.6, but the latest version (2.0.7) resolved this problem for me, if you're still getting this.
