### ISSUE TITLE
Rainmeter not working.....

### ISSUE THREAD

**Issue by Senpai899** [adlerluiz/ytmdesktop#1365]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The rainmeter integration option is missing on the latest version which was useful for me on the older version.

### Expected Behavior

I need to see track and author info on rainmeter skins.

### Steps To Reproduce

....

### YTMDesktop

2.0.5

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

![Screenshot 2024-05-29 014300](https://github.com/ytmdesktop/ytmdesktop/assets/73914237/9eb21437-2a46-4125-b261-bcab5081da96)
![Screenshot 2024-05-29 014324](https://github.com/ytmdesktop/ytmdesktop/assets/73914237/641ad776-c2e4-4e6b-92ad-a36dd8625e2e)

**Comment by Alipoodle** [comment]
[#1139 With Comment Highlighted](https://github.com/ytmdesktop/ytmdesktop/issues/1139#:~:text=However%20this%20also%20means%0AThat%20some%20features%20have%20not%20yet%20been%20ported%20over%20yet%2C%20including%3A) As mentioned we've removed a lot of things.

Rainmeter has also since updated a lot of their features with WebNowPlaying Redux which is a FAR better solution by using the Windows Media service API instead of manually providing a websocket for the data.

**Comment by Alipoodle** [comment]
https://wnp.keifufu.dev/rainmeter/usage

This is the example Media Player they provide, and will work functionally with ANY thing which uses the Windows Media Service.

**Comment by Alipoodle** [comment]
No further conversation, and Rainmeter and others have since updated to better methods for using Media service.
