### ISSUE TITLE
YouTube.Music.Desktop.App-2.0.5.Setup.exe malware by some antivirus

### ISSUE THREAD

**Issue by superbonaci** [adlerluiz/ytmdesktop#1386]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

some antivirus detect the installer as virus:

https://www.virustotal.com/gui/file/c1f4b5826d8c234dea07581307ff78b589f5358a1169bb28afe879bb038fadb2

### Expected Behavior

no virus

### Steps To Reproduce

none

### YTMDesktop

v2.0.5

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment]
https://github.com/ytmdesktop/ytmdesktop/issues/1358
As to repeat:

> ### DO NOT take my word for anything said here. Please make your own judgement decision even though I'm a maintainer.
> 
> This is a false positive from a singular vendor on VirusTotal that's likely very aggressive. Your antivirus as such is likely also being aggressive. Many applications depending what they do get flagged by specific aggressive vendors for various reasons. There is "nothing" we can do to really correct them.
>
> For further context for others reading this issue [here's the VirusTotal link for the file in question](https://www.virustotal.com/gui/file/c1f4b5826d8c234dea07581307ff78b589f5358a1169bb28afe879bb038fadb2).

The application does a few things like attempt to read the YTMDv1's config to migrate users from v1 -> v2, which can be deemed as sketchy as it's trying to read files outside of it's own folders.

You have 100% decision to decide if you wish to trust your own decision and use the application, or follow your Anti-Virus and not install us.

**Comment by kissu** [comment]
I have this by default on MacOS tho, no anti-virus or anything installed.
Doesn't inspire a lot of trust from the get-go.

Why does it even try to read outside of its own folders to begin with?? 🤷‍♂ 
Idk how people manage to have v1 -> v2 bumps but definitely better ways to handle it than just accessing someone's system IMHO.

**Comment by Akiisqt** [comment]
All of its code is open to read, please try the updated version to see if the issue persists

**Comment by Alipoodle** [comment]
@kissu

> Why does it even try to read outside of its own folders to begin with?? 🤷‍♂

This has been an application which has been going on for a LONG time, and the v1 version of the application has had it's fair share of downloads. [You can see this on the home page as 12 million, which is gathered from the downloads from GitHub Releases. [So doesn't include the few places which package + distrobute the app themselves, although rare]

When we decided to migrate people over to a v2 version of the application, Our process changed for how we have packaged the application, and in turn this caused a few things which caused this.

A) We didn't want to FORCE people on to v2 at the time, we wanted people to still have access to v1 while it was in a functional state. It had more features, but had issues with Security. This way people had the opportunity to try V2, without uninstalling their existing application.
B) We moved Build processes from Electron-packager to Electron-Forge (this does still use packager, but in a different way) which caused some things like changing how the folder name was saved in Users `%appdata%` or similar.
C) Migrating users. When we have some of the features before, why not copy them on a first time setup to read their previous version of the application and instantly have setup for the v2 application smooth transition.

## The Future
We plan to remove the Migration thing soon, considering the V1 of the application is no longer functional due to changes within YTM breaking core elements of how the application used to work. V1 is using an hugely outdated version of Electron and some poor methods of fetching information, so we knew it was a ticking clock before it broke.

And as was mentioned within the thing. Trust us if you want...  False positives exist, it's an open source project (so build it yourself if you want). You have your own opinion in this thing and if you choose to not use us, fine. YTM works in a browser still.

**Comment by kissu** [comment]
Few points:
- package downloads doesn't really matter, hence 12M or 13k is the same to the end users (reminder: my comment was about the use of higher privileges not the popularity)
- if you don't want to force people to move, feel free to display a prompt + an export/import feature for a v1/v2 migration
- "had more features, but had issues with Security" >> hence we should ignore that security prompt? Weird and unrelated take IMO.
- move towards Electron-Forge: again, I don't see why both versions should co-exist and make security dirty, all but inspiring trust.
- migrating users: sure, 100 ways of pushing them to move to the new LTS
- I know it's FOSS, this doesn't mean that I would like to spend time bundling it myself locally
- given the state of the project, I anyway don't think that it would add too much value VS the PWA so I'll skip this project whatsoever, mostly wanted to provide some feedback regarding a first (potential) user
- as a whole, if you want people to trust your project more please make it working flawlessly from the start without introducing any security/privacy concerns from the install script 💖

**Comment by Alipoodle** [comment]
Enjoy the PWA!
