### ISSUE TITLE
Open YTM links in app

### ISSUE THREAD

**Issue by Lexizz7** [adlerluiz/ytmdesktop#1406]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

YTM links clicked in external applications should open in app instead of opening in default browser.
And the arrow back should go back to whenever you were.

### Anything else?

When I click a song link shared by a friend, it opens in my default browser creating more and more tabs. Its unorganized.
It would be cool if it opened in YTM desktop app instead, like Spotify does.

**Comment by NovusTheory** [comment]
We have an old [tamper monkey script](https://github.com/ytmdesktop/YTMD-opener-tampermonkey/blob/master/src.js) that adds a button to YTM in your browser to open on YTMD. Not sure if this still works as this script isn't maintained.

**Comment by Alipoodle** [comment]
_last I checked it did work with both V1 & V2_

However for an Android style of *Supported Links* which I'm suspect you are looking for. This would require us to overwrite the HTTP/HTTPS protocol to process the link.
Which feels a bit intrusive and overkill.

**Comment by Lexizz7** [comment]
I was thinking on just add support to `Apps for websites` in Windows 11.
Apps like Spotify, Microsoft Teams, and others have this funcionality.

![image](https://github.com/user-attachments/assets/8e02cff7-058c-44b9-b8b0-3182d7181b62)

If you don't have the app, it just open the browser by default. It's not a custom protocol like `ytmd://`

**Comment by NovusTheory** [comment]
> I was thinking on just add support to Apps for websites in Windows 11

Outside of the tamper monkey script we cannot add an "Apps for websites" entry. This not only requires becoming a Windows App instead of a generic Win32 program it *also* requires the server (in this case YTM) to contain a file which says that app can be used to open links. See Spotify's at https://open.spotify.com/.well-known/windows-app-web-link.

Given these circumstances I'm going to close as won't fix since this isn't something we can do outside what @Alipoodle said above with making YTMD your default browser which we're not a browser so that won't happen.
