### ISSUE TITLE
[Query] Mini player for V2

### ISSUE THREAD

**Issue by Adam-Kay** [adlerluiz/ytmdesktop#1420]
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature / Query

Hello, I just wanted to ask if the mini player was on the radar for the v2 version of the YTM Desktop player. I saw a small reference to it in the [announcement post](https://github.com/ytmdesktop/ytmdesktop/issues/1139#issue-1820093275) but since then I haven't seen it mentioned anywhere. I use it all the time and its absence from v2 is the main reason I'm hesitant to upgrade from v1.

**Comment by harsh251004** [comment]
yes, v2 will make its return in the future ytmdesktop versions for now it is kept on hold. But definitely it will make its comeback.

**Comment by Akiisqt** [comment]
Whats the miniplayer exactly?

**Comment by Adam-Kay** [comment]
> *@Akiisqt* 
> Whats the miniplayer exactly?

It's a feature from the v1 version of the app that let you have a miniature media player. 
You could activate it with this button in the UI:
![image](https://github.com/user-attachments/assets/be60bdff-2746-4384-a604-e13d1e19cf90)

and once activated it would look like this:
| Standard | On Hover |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/e29e2558-9d29-4391-b2a4-b477b6e0a83f) | ![image](https://github.com/user-attachments/assets/054b3e43-a1f4-452f-a5b5-669cae975ca5) |

**Comment by Alipoodle** [comment]
This actually came up in our internal chat the night before this was posted.

Electron supports *Video* Picture in picture like Chrome does currently! ☺️
But the Audio only (which I feel more people are using and want) is something we wanted to support via Document Picture in picture. Although we suspect that this isn't going to get fixed with electron.

So there plans to start this as a new Window like before. 😘

**Comment by jayDB5** [comment]
+1 to the list of people who would love for this feature to come back! ☺️
